name: CI

on: [push]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
          submodules: true
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=debug ..
    - name: format
      run: cmake --build build --target check-format
    - name: build
      run: cmake --build build
    - name: test
      run: cd build && ctest
